name: Lock Closed Threads
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
      - uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '90'
          pr-inactive-days: '90'
          discussion-inactive-days: '90'
          log-output: true
